spring:
  datasource:
    url: jdbc:mysql://localhost:3307/gardf?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nourbel1510@gmail.com}
    password: ${MAIL_PASSWORD:veikbyqewclbgzgj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          bertService:
            baseConfig: default
            circuitBreakerConfig:
              failureRateThreshold: 50
              minimumNumberOfCalls: 5
              slidingWindowType: COUNT_BASED
              slidingWindowSize: 10
              automaticTransitionFromOpenToHalfOpenEnabled: true
              waitDurationInOpenState: 5s

konnect:
  api:
    url: https://api.konnect.network/api/v2
    key: ${KONNECT_API_KEY}
  wallet:
    id: ${KONNECT_WALLET_ID}
  callback:
    url: http://localhost:8081/api/payment/callback

server:
  port: 8081
